[ [ { Choice_ID: 382,
      Question_ID: 277,
      ChoiceOrder: 1,
      IsCorrectChoice: 'N',
      Content: 'Leonardo Di Caprio',
      Poll_ID: 53,
      Stem: 'Who is your favorite actor?',
      AnswerType: 'MultipleChoice',
      QuestionsOrder: 1 },
    { Choice_ID: 383,
      Question_ID: 277,
      ChoiceOrder: 2,
      IsCorrectChoice: 'N',
      Content: 'Tom Hanks',
      Poll_ID: 53,
      Stem: 'Who is your favorite actor?',
      AnswerType: 'MultipleChoice',
      QuestionsOrder: 1 },
    { Choice_ID: 384,
      Question_ID: 277,
      ChoiceOrder: 3,
      IsCorrectChoice: 'N',
      Content: 'Julia Roberts',
      Poll_ID: 53,
      Stem: 'Who is your favorite actor?',
      AnswerType: 'MultipleChoice',
      QuestionsOrder: 1 },
    { Choice_ID: 385,
      Question_ID: 277,
      ChoiceOrder: 4,
      IsCorrectChoice: 'N',
      Content: 'Daniel Craig',
      Poll_ID: 53,
      Stem: 'Who is your favorite actor?',
      AnswerType: 'MultipleChoice',
      QuestionsOrder: 1 } ],
  { Choice_ID: null,
    Question_ID: 279,
    ChoiceOrder: null,
    IsCorrectChoice: null,
    Content: null,
    Poll_ID: 53,
    Stem: 'If you could be any animal what would you be?',
    AnswerType: 'FreeResponse',
    QuestionsOrder: 2 },
  { Choice_ID: null,
    Question_ID: 278,
    ChoiceOrder: null,
    IsCorrectChoice: null,
    Content: null,
    Poll_ID: 53,
    Stem: 'How was your weekend?',
    AnswerType: 'FreeResponse',
    QuestionsOrder: 3 },
  { Choice_ID: 387,
    Question_ID: 282,
    ChoiceOrder: 1,
    IsCorrectChoice: 'F',
    Content: 'False',
    Poll_ID: 53,
    Stem: 'Dolphins can smell',
    AnswerType: 'TrueFalse',
    QuestionsOrder: 4 },
  { Choice_ID: 386,
    Question_ID: 281,
    ChoiceOrder: 1,
    IsCorrectChoice: 'T',
    Content: 'True',
    Poll_ID: 53,
    Stem: 'You are TRUE!',
    AnswerType: 'TrueFalse',
    QuestionsOrder: 5 },
  { Choice_ID: null,
    Question_ID: 280,
    ChoiceOrder: null,
    IsCorrectChoice: null,
    Content: null,
    Poll_ID: 53,
    Stem: 'How many legs does a centipede have?',
    AnswerType: 'Numeric',
    QuestionsOrder: 6 } ]